apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: shop
  labels:
    app: shop
data:
  # Backend env vars
  NODE_ENV: "production"
  BACKEND_PORT: "5000"
  FRONTEND_PORT: "3000"
  # Frontend talks to backend via K8s internal DNS
  BACKEND_URL: "http://backend.shop.svc.cluster.local:5000"
  # Frontend (React) env vars
  REACT_APP_CLOUD_NAME_CLOUDINARY: "dal7ers5p"
  # Will be replaced after LoadBalancer is provisioned
  FRONTEND_URL: "http://localhost:3000"
